"""Camshaft hero cover — a metal camshaft entering the atmosphere.

Kimi-blog aesthetic: near-black backdrop, single luminous subject, iridescent
rim lighting, heavy motion blur. The subject is a literal automotive camshaft
(shaft + cam lobes) streaking horizontally with plasma heat on the leading edge
and long motion-blur trails behind.
"""
from __future__ import annotations

import math
import random
from PIL import Image, ImageDraw, ImageFilter

WIDTH, HEIGHT = 1920, 1080
OUT_PATH = "/Users/michaelwong/Developer/Camshaft/docs/screenshot.png"

BG = (3, 3, 6)

# Rim-light palette — cool blue/violet on top, warm amber/coral on bottom
COOL = (110, 165, 255)
VIOLET = (170, 140, 255)
MAGENTA = (230, 140, 200)
AMBER = (255, 170, 110)
WARM = (255, 120, 90)
PLASMA = (255, 220, 180)  # near-white plasma core

# Metal palette
STEEL_DARK = (40, 44, 54)
STEEL_MID = (110, 118, 132)
STEEL_HIGHLIGHT = (210, 215, 225)

random.seed(5)


def solid_bg() -> Image.Image:
    img = Image.new("RGB", (WIDTH, HEIGHT), BG).convert("RGBA")

    # Very soft warm atmospheric glow near leading edge (right side)
    glow = Image.new("RGBA", (WIDTH, HEIGHT), (0, 0, 0, 0))
    d = ImageDraw.Draw(glow)
    d.ellipse(
        [WIDTH // 2 + 100, HEIGHT // 2 - 500, WIDTH + 400, HEIGHT // 2 + 500],
        fill=(*AMBER, 40),
    )
    glow = glow.filter(ImageFilter.GaussianBlur(radius=220))
    img.alpha_composite(glow)

    # Cool haze on trailing (left) side
    cool = Image.new("RGBA", (WIDTH, HEIGHT), (0, 0, 0, 0))
    d = ImageDraw.Draw(cool)
    d.ellipse(
        [-400, HEIGHT // 2 - 450, WIDTH // 2 - 100, HEIGHT // 2 + 450],
        fill=(*COOL, 22),
    )
    cool = cool.filter(ImageFilter.GaussianBlur(radius=220))
    img.alpha_composite(cool)

    return img


def draw_camshaft_silhouette(size: tuple[int, int]) -> Image.Image:
    """Draw a clean camshaft silhouette mask — pure black subject on transparent.

    Geometry: horizontal shaft with rounded ends + 3 teardrop cam lobes
    alternating up/down along its length. This is the MASK — rim lighting
    is added separately.
    """
    w, h = size
    layer = Image.new("RGBA", (w, h), (0, 0, 0, 0))
    cy = h // 2
    shaft_radius = h // 5
    shaft_top = cy - shaft_radius
    shaft_bot = cy + shaft_radius

    draw = ImageDraw.Draw(layer)

    # Main shaft: rounded rectangle
    draw.rounded_rectangle(
        [shaft_radius, shaft_top, w - shaft_radius, shaft_bot],
        radius=shaft_radius,
        fill=(10, 10, 14, 255),
    )

    # 3 teardrop cam lobes — up, down, up
    lobe_positions = [(0.22, -1), (0.52, 1), (0.82, -1)]
    for p, direction in lobe_positions:
        cx_px = int(w * p)
        lobe_w = int(h * 0.42)
        lobe_h = int(h * 0.85)

        if direction == -1:  # up
            lobe_box = [cx_px - lobe_w, cy - lobe_h, cx_px + lobe_w, cy + int(h * 0.05)]
        else:  # down
            lobe_box = [cx_px - lobe_w, cy - int(h * 0.05), cx_px + lobe_w, cy + lobe_h]

        draw.ellipse(lobe_box, fill=(10, 10, 14, 255))

    return layer


def add_rim_light(mask: Image.Image, color_leading: tuple[int, int, int], color_cool: tuple[int, int, int]) -> Image.Image:
    """Given a dark silhouette, add bright rim lighting on all edges.

    Leading edge (right) gets hot plasma color, trailing (left) and top get
    cool color. Rim is generated by expanding the silhouette, blurring, and
    subtracting the original.
    """
    w, h = mask.size
    alpha = mask.split()[3]

    # Full outer glow (halo around silhouette) — cool
    outer = Image.new("RGBA", (w, h), (0, 0, 0, 0))
    outer_px = outer.load()
    for y in range(h):
        for x in range(w):
            pass  # placeholder — we use alpha instead below
    outer = Image.new("RGBA", (w, h), (*color_cool, 0))
    outer.putalpha(alpha)
    # Blur the alpha to create glow
    glow_alpha = alpha.filter(ImageFilter.GaussianBlur(radius=18))
    outer.putalpha(Image.eval(glow_alpha, lambda v: min(v * 2, 255)))

    # Leading-edge hot rim — skew the color toward amber/warm on the right
    hot = Image.new("RGBA", (w, h), (*color_leading, 0))
    hot_alpha = Image.eval(alpha, lambda v: v)
    # Create a horizontal gradient mask that's strong on the right half only
    grad = Image.new("L", (w, h), 0)
    gpx = grad.load()
    for x in range(w):
        t = x / (w - 1)
        val = int(255 * max(0.0, (t - 0.35) / 0.65) ** 1.5)
        for y in range(h):
            gpx[x, y] = val
    # Blur alpha then mask by horizontal gradient
    hot_glow = alpha.filter(ImageFilter.GaussianBlur(radius=14))
    combined = Image.eval(hot_glow, lambda v: v)
    combined = Image.merge("L", (combined,)) if combined.mode != "L" else combined
    # Multiply by gradient
    final_alpha = Image.new("L", (w, h), 0)
    fpx = final_alpha.load()
    hg = hot_glow.load()
    for x in range(w):
        for y in range(h):
            fpx[x, y] = (hg[x, y] * gpx[x, y]) // 255
    hot.putalpha(final_alpha)

    # Combine outer + hot
    result = Image.new("RGBA", (w, h), (0, 0, 0, 0))
    result.alpha_composite(outer)
    result.alpha_composite(hot)

    # Subtract the interior (keep only the rim, not the fill)
    # Erode the alpha by blurring less, then subtract
    interior = alpha.filter(ImageFilter.GaussianBlur(radius=0))  # crisp
    erode_mask = Image.new("L", (w, h), 0)
    erode_px = erode_mask.load()
    alpha_px = alpha.load()
    for x in range(w):
        for y in range(h):
            # Keep rim: if alpha is edge (not fully inside nor fully outside)
            erode_px[x, y] = alpha_px[x, y]
    # Multiplicative: keep glow only where silhouette alpha is LOW
    keep_mask = Image.eval(alpha, lambda v: 255 - v)
    result_alpha = result.split()[3]
    masked = Image.new("L", (w, h), 0)
    mpx = masked.load()
    rpx = result_alpha.load()
    kpx = keep_mask.load()
    for x in range(w):
        for y in range(h):
            mpx[x, y] = (rpx[x, y] * kpx[x, y]) // 255
    result.putalpha(masked)

    return result


def apply_motion_blur(img: Image.Image, length: int, samples: int = 18) -> Image.Image:
    """Approximate horizontal motion blur by averaging horizontally-offset copies."""
    w, h = img.size
    accum = Image.new("RGBA", (w + length * 2, h), (0, 0, 0, 0))
    for i in range(samples):
        t = i / (samples - 1)
        offset = int((t - 0.5) * length)
        frame = img.copy()
        # Fade the extremes so head stays sharp, tail dissolves
        frame.putalpha(
            Image.eval(frame.split()[3], lambda v: int(v * (1.0 / samples) * 2.0))
        )
        accum.alpha_composite(frame, (length + offset, 0))
    return accum


def streaking_trails(canvas: Image.Image, cx: int, cy: int, width: int, height: int) -> None:
    """Long horizontal plasma trails behind the subject, fading into the void."""
    trail = Image.new("RGBA", canvas.size, (0, 0, 0, 0))
    d = ImageDraw.Draw(trail)
    # Multiple overlapping horizontal streaks at different y offsets
    offsets = [-60, -30, -12, 0, 14, 32, 58]
    colors = [COOL, VIOLET, MAGENTA, PLASMA, AMBER, WARM, (255, 90, 70)]
    for dy, color in zip(offsets, colors):
        # Trail goes LEFT from leading edge
        trail_w = width * 3
        trail_h = 6
        start_x = cx - trail_w
        end_x = cx
        y = cy + dy
        # Gradient alpha along length — bright at head, fading at tail
        layer = Image.new("RGBA", (trail_w, trail_h * 12), (0, 0, 0, 0))
        lpx = layer.load()
        for lx in range(trail_w):
            t = lx / max(trail_w - 1, 1)  # 0 at far tail, 1 at head
            head_t = t ** 2.5  # concentrate near head
            for ly in range(trail_h * 12):
                ny = (ly - trail_h * 6) / (trail_h * 6)
                vert = max(0.0, 1.0 - abs(ny) ** 1.4)
                alpha = int(255 * head_t * vert * 0.9)
                if alpha <= 0:
                    continue
                lpx[lx, ly] = (color[0], color[1], color[2], alpha)
        blurred = layer.filter(ImageFilter.GaussianBlur(radius=10))
        canvas.alpha_composite(blurred, (start_x, y - trail_h * 6))

    canvas.alpha_composite(trail)


def plasma_leading_edge(canvas: Image.Image, cx: int, cy: int, size: int) -> None:
    """Bright plasma heat shield on the leading (right) edge of the camshaft."""
    # Layered glows — plasma white core, amber mid, coral outer
    layers = [
        (size * 3, (255, 90, 70, 55)),
        (size * 2, (255, 160, 100, 75)),
        (size + size // 2, (255, 220, 180, 110)),
        (size, (255, 255, 240, 180)),
    ]
    for r, color in layers:
        g = Image.new("RGBA", canvas.size, (0, 0, 0, 0))
        gd = ImageDraw.Draw(g)
        gd.ellipse([cx - r, cy - r, cx + r, cy + r], fill=color)
        g = g.filter(ImageFilter.GaussianBlur(radius=r // 5))
        canvas.alpha_composite(g)

    # Core white-hot spot
    core = Image.new("RGBA", canvas.size, (0, 0, 0, 0))
    cd = ImageDraw.Draw(core)
    cd.ellipse([cx - 26, cy - 26, cx + 26, cy + 26], fill=(255, 255, 250, 255))
    core = core.filter(ImageFilter.GaussianBlur(radius=6))
    canvas.alpha_composite(core)


def spark_debris(canvas: Image.Image, cx: int, cy: int, count: int = 140) -> None:
    """Hot spark particles streaking behind the camshaft."""
    layer = Image.new("RGBA", canvas.size, (0, 0, 0, 0))
    d = ImageDraw.Draw(layer)
    for _ in range(count):
        # Spawn behind the leading edge, biased toward center axis
        dx = random.randint(-int(WIDTH * 0.55), 0)
        dy = int(random.gauss(0, 70))
        x = cx + dx
        y = cy + dy
        # Streak length grows with distance from head (older sparks are longer + dimmer)
        age = abs(dx) / (WIDTH * 0.55)
        length = int(20 + age * 160)
        alpha = int(220 * (1 - age) ** 1.2)
        if alpha <= 0:
            continue
        color = random.choice([PLASMA, AMBER, WARM, (255, 230, 190)])
        d.line([(x, y), (x + length, y)], fill=(*color, alpha), width=1)
    layer = layer.filter(ImageFilter.GaussianBlur(radius=0.6))
    canvas.alpha_composite(layer)


def chromatic_rim(canvas: Image.Image, cx: int, cy: int, length: int) -> None:
    """Horizontal chromatic dispersion band under the subject."""
    cool = Image.new("RGBA", canvas.size, (0, 0, 0, 0))
    d = ImageDraw.Draw(cool)
    d.ellipse(
        [cx - length // 2, cy - 160, cx + length // 2, cy - 20],
        fill=(*COOL, 55),
    )
    cool = cool.filter(ImageFilter.GaussianBlur(radius=90))
    canvas.alpha_composite(cool)

    warm = Image.new("RGBA", canvas.size, (0, 0, 0, 0))
    d = ImageDraw.Draw(warm)
    d.ellipse(
        [cx - length // 2, cy + 20, cx + length // 2, cy + 160],
        fill=(*WARM, 50),
    )
    warm = warm.filter(ImageFilter.GaussianBlur(radius=90))
    canvas.alpha_composite(warm)


def particle_dust(canvas: Image.Image, count: int = 45) -> None:
    layer = Image.new("RGBA", canvas.size, (0, 0, 0, 0))
    d = ImageDraw.Draw(layer)
    for _ in range(count):
        x = random.randint(0, WIDTH)
        y = random.randint(0, HEIGHT)
        r = random.choice([1, 1, 2])
        alpha = random.randint(15, 70)
        d.ellipse([x - r, y - r, x + r, y + r], fill=(240, 240, 255, alpha))
    canvas.alpha_composite(layer.filter(ImageFilter.GaussianBlur(radius=0.4)))


def film_grain(canvas: Image.Image, amount: int = 5500) -> None:
    noise = Image.new("RGBA", canvas.size, (0, 0, 0, 0))
    px = noise.load()
    for _ in range(amount):
        x = random.randint(0, WIDTH - 1)
        y = random.randint(0, HEIGHT - 1)
        v = random.randint(0, 30)
        a = random.randint(20, 55)
        px[x, y] = (v, v, v, a)
    canvas.alpha_composite(noise)


def main() -> None:
    canvas = solid_bg()

    # Composition:
    # - Camshaft occupies middle-right horizontally, slight vertical center
    # - Leading edge (right) has plasma heat shield
    # - Trails + sparks extend left across most of the canvas
    shaft_w = 720
    shaft_h = 160
    shaft_x = WIDTH // 2 - 120  # shifted slightly right-of-center
    shaft_y = HEIGHT // 2 - shaft_h // 2
    shaft_center_x = shaft_x + shaft_w // 2
    shaft_center_y = shaft_y + shaft_h // 2
    leading_edge_x = shaft_x + shaft_w
    leading_edge_y = shaft_center_y

    # 1. Chromatic rim under/above shaft — full-canvas width for drama
    chromatic_rim(canvas, shaft_center_x, shaft_center_y, length=2200)

    # 2. Long horizontal streaking trails (behind, pointing left)
    streaking_trails(canvas, leading_edge_x, shaft_center_y, shaft_w, shaft_h)

    # 3. Spark debris
    spark_debris(canvas, leading_edge_x, shaft_center_y, count=160)

    # 4. Camshaft SILHOUETTE + rim lighting (dark subject, glowing edges)
    # Render slightly taller canvas so rim has room to bloom
    pad = 80
    cam_w = shaft_w + pad * 2
    cam_h = shaft_h + pad * 2
    cam_layer = Image.new("RGBA", (cam_w, cam_h), (0, 0, 0, 0))
    silhouette = draw_camshaft_silhouette((shaft_w, shaft_h))
    cam_layer.alpha_composite(silhouette, (pad, pad))

    # Rim light
    rim = add_rim_light(cam_layer, color_leading=AMBER, color_cool=COOL)

    # Motion blur the rim for that long-exposure feel
    smear_samples = 40
    smear_length = 520
    smear = Image.new("RGBA", canvas.size, (0, 0, 0, 0))
    for i in range(smear_samples):
        t = i / (smear_samples - 1)
        offset_x = int(-smear_length * (1 - t))
        # Stronger at head, fading toward tail
        opacity_factor = (t ** 2.0) * 12.0 / smear_samples
        frame = rim.copy()
        frame.putalpha(
            Image.eval(
                frame.split()[3],
                lambda v, o=opacity_factor: min(int(v * o), 255),
            )
        )
        smear.alpha_composite(frame, (shaft_x - pad + offset_x, shaft_y - pad))
    smear = smear.filter(ImageFilter.GaussianBlur(radius=3))
    canvas.alpha_composite(smear)

    # Crisp silhouette + rim on top so the subject reads cleanly at head
    canvas.alpha_composite(cam_layer, (shaft_x - pad, shaft_y - pad))
    canvas.alpha_composite(rim, (shaft_x - pad, shaft_y - pad))

    # 6. Plasma heat shield on the leading edge — large and dominant
    plasma_leading_edge(canvas, leading_edge_x + 10, leading_edge_y, size=180)

    # 7. Extra motion trails streaming from leading edge (short, bright)
    head_streaks = Image.new("RGBA", canvas.size, (0, 0, 0, 0))
    d = ImageDraw.Draw(head_streaks)
    for _ in range(80):
        y = shaft_center_y + int(random.gauss(0, 40))
        length = random.randint(80, 240)
        alpha = random.randint(60, 170)
        color = random.choice([PLASMA, AMBER, WARM])
        start = leading_edge_x + 20 - length
        d.line([(start, y), (leading_edge_x + 10, y)], fill=(*color, alpha), width=1)
    head_streaks = head_streaks.filter(ImageFilter.GaussianBlur(radius=1.2))
    canvas.alpha_composite(head_streaks)

    # 8. Minimal dust + grain
    particle_dust(canvas, count=40)
    film_grain(canvas, amount=5200)

    # 9. Final vignette
    vignette_mask = Image.new("L", (WIDTH, HEIGHT), 0)
    vd = ImageDraw.Draw(vignette_mask)
    vd.ellipse([-500, -500, WIDTH + 500, HEIGHT + 500], fill=255)
    vignette_mask = vignette_mask.filter(ImageFilter.GaussianBlur(radius=240))
    dark = Image.new("RGBA", canvas.size, (0, 0, 0, 160))
    inv = Image.eval(vignette_mask, lambda v: 255 - v)
    dark.putalpha(inv)
    canvas.alpha_composite(dark)

    final = canvas.convert("RGB")
    final.save(OUT_PATH, "PNG", optimize=True)
    import os

    print(f"Saved: {OUT_PATH} ({WIDTH}x{HEIGHT}, {os.path.getsize(OUT_PATH)/1024:.1f} KB)")


if __name__ == "__main__":
    main()
